version: '2'
services:

  app:
    image: openjdk:8-jdk
    volumes:
      - .:/app
      - .gradle/:/root/.gradle/
    working_dir: /app
    command: ./gradlew clean bootRun
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis

  redis:
    image: redis
    ports:
      - "6379:6379"
